---
apiVersion: v1
kind: Service
metadata:
  name: adabas-db
spec:
  type: ClusterIP
  selector:
    app: adabas-db
  ports:
    - name: db-port
      protocol: TCP
      port: 60001
      targetPort: db-port
