---
apiVersion: v1
kind: Service
metadata:
  name: employees-service
spec:
  type: ClusterIP
  selector:
    app: employees
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
