---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-service-deployment
  labels:
    app: employees
    tier: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: employees
      tier: backend
  template:
    metadata:
      labels:
        app: employees
        tier: backend
    spec:
      containers:
      - name: employees-service
        image: miketrout/employees-service
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 80
