---
apiVersion: v1
kind: Service
metadata:
  name: employees-service
spec:
  type: NodePort
  selector:
    app: employees
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 50003
      targetPort: http
