---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-service-deployment
  labels:
    app: employees
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      tier: backend
  template:
    metadata:
      labels:
        app: employees
        tier: backend
    spec:
      containers:
        - name: employees-service
          image: miketrout/employees-service
          resources:
            requests:
              memory: 50Mi
              cpu: 10m
            limits:
              memory: 100Mi
              cpu: 50m
          ports:
            - name: http
              containerPort: 80
